root_path: "/home/labs/fleishman/omripo/fitness_learning"
# dataset_path: "/home/labs/fleishman/omripo/fitness_learning/data/PTE/funclib_llm_input.csv"
dataset_path: "/home/labs/fleishman/omripo/fitness_learning/data/PTE/dataset.csv"
save_path: "/home/labs/fleishman/omripo/fitness_learning/pretraining/PTE/models/unsupervised_v3"
bootstrap_path: "/home/labs/fleishman/omripo/fitness_learning/pretraining/PTE/bootstrap/"
weights_path: "/home/labs/fleishman/omripo/fitness_learning/pretraining/PTE/models/final_model.pt"

model_type: "plm"
train_type: "msa_backbone"

# Strings
nmuts_column: "num_muts"
sequence_column_name: "full_seq"
activity_column_name: "inactive"
first_column_name: "I106"
last_column_name: "M317"
plm_name: "esm2_t12_35M_UR50D"
ref_seq: "ITNSGDRINTVRGPITISEAGFTLMHEHICGSSAGFLRAWPEFFGSRDALAEKAVRGLRRARAAGVRTIVDVSTFDIGRDVELLAEVSEAADVHIVAATGLWFDPPLSMRLRSVEELTQFFLREIQYGIEDTGIRAGIIKVATTGKATPFQERVLRAAARASLATGVPVTTHTDASQRDGEQQADIFESEGLDPSRVCIGHSDDTDDLDYLTALAARGYLIGLDHIPHSAIGLEDNASAAALLGLRSWQTRALLIKALIDQGYADQILVSNDWLFGFSSYVTNIMDVMDRVNPDGMAFIPLRVIPFLREKGVPDETLETIMVDNPARFLSPTLRAS"
# ref_seq: "DRINTVRGPITISEAGFTLTHEHICGSSAGFLRAWPEFFGSRKALAEKAVRGLRRARAAGVRTIVDVSTFDIGRDVSLLAEVSRAADVHIVAATGLWFDPPLSMRLRSVEELTQFFLREIQYGIEDTGIRAGIIKVATTGKATPFQELVLKAAARASLATGVPVTTHTAASQRDGEQQAAIFESEGLSPSRVCIGHSDDTDDLSYLTALAARGYLIGLDHIPHSAIGLEDNASASALLGIRSWQTRALLIKALIDQGYMKQILVSNDWLFGFSSYVTNIMDVMDRVNPDGMAFIPLRVIPFLREKGVPQETLAGITVTNPARFLSPTLRAS"
bootstrap_indices_prefix: "indices"
enzyme: "PTE"
substrate: "p-nitrophenyl_acetate"

# Lists
train_indices: "all"
train_fraction: 0.8
test_indices: [6]
# pos_to_use: [106, 132, 254, 257, 271, 303, 306, 317] 
# pos_to_use: [72, 98, 220, 223, 237, 269, 272, 283]  # FOR WT PTE NEED TO SUBTRACT 34
pos_to_use: [77, 103, 225, 228, 242, 274, 277, 288] # FOR WT dPTE_2 NEED TO SUBTRACT 29

# Booleans
load_weights: False
train: True
train_indices_rev: False
test_indices_rev: False
evaluate_train: False 
evaluate_test: False
train_drop_tokens: True
inference_drop_tokens: False


# Integers
lr: 4e-6
batch_size: 128
iterations: 2000
n_bootstrap: 1000