root_path: "/home/labs/fleishman/itayta/fitness/"
dataset_path: "retraining_esm/gfp_dataset.csv"
save_path: "pretraining/esm650m/"
weights_path: "pretraining/esm650m/"


model_type: "plm"
train_type: "triplet"

# Strings
nmuts_column: "num_muts"
sequence_column_name: "full_seq"
label_column_name: "inactive"
first_column_name: "L42"
last_column_name: "V224"
plm_name: "esm2_t33_650M_UR50D"
ref_seq: "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRYPDHMKRHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKTRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYN"


# Lists
train_indices: [1,2,3,4]
test_indices: [5]
pos_to_use: [42, 44, 61, 65, 68, 69, 72, 94, 108, 112, 121, 145, 148, 150, 167, 181, 185, 203, 205, 220, 222, 224]

# Booleans
load_weights: False
train: True
train_indices_rev: False
test_indices_rev: False
evaluate_train: False 
evaluate_test: False
train_drop_tokens: True
inference_drop_tokens: False
flat_embeddings: False

# Integersx
lr: 5e-7
batch_size: 16 
iterations: 12000

