root_path: "/home/labs/fleishman/omripo/Projects/adaptive_learning"
data_dir_name: "data"
pretraining_dir_name: "pretraining"
bootstrap_dir_name: "bootstrap"
results_dir_name: "results"
enzyme: "PTE"
substrate: "malathion"

dataset_filename: "test_dataset.csv"
tag: "test"
weights_filename: "final_model.pt"

model_type: "plm"
finetune: False
opmode: "mean"
train_type: "msa_backbone"

# Strings
nmuts_column: "num_muts"
sequence_column_name: "full_seq"
activity_column_name: "inactive"
first_column_name: "I106"
last_column_name: "M317"
plm_name: "esm2_t12_35M_UR50D"
ref_seq: "DRINTVRGPITISEAGFTLTHEHICGSSAGFLRAWPEFFGSRKALAEKAVRGLRRARAAGVRTIVDVSTFDIGRDVSLLAEVSRAADVHIVAATGLWFDPPLSMRLRSVEELTQFFLREIQYGIEDTGIRAGIIKVATTGKATPFQELVLKAAARASLATGVPVTTHTAASQRDGEQQAAIFESEGLSPSRVCIGHSDDTDDLSYLTALAARGYLIGLDHIPHSAIGLEDNASASALLGIRSWQTRALLIKALIDQGYMKQILVSNDWLFGFSSYVTNIMDVMDRVNPDGMAFIPLRVIPFLREKGVPQETLAGITVTNPARFLSPTLRAS"
bootstrap_indices_prefix: "indices"

# Lists
train_indices: "all"
train_fraction: 0.8
test_indices: [6]
pos_to_use: [72, 98, 220, 223, 237, 269, 272, 283]  # FOR WT PTE NEED TO SUBTRACT 34
hidden_layers: [512,256]

# Booleans
load_weights: False
train: True
train_indices_rev: False
test_indices_rev: False
evaluate_train: False 
evaluate_test: False
train_drop_tokens: True
inference_drop_tokens: False


# Integers
lr: 4e-6
batch_size: 64
iterations: 500
n_bootstrap: 1000
bootstrap_hidden_layer_size: 128
test_fraction: 0.3